name: "⚙️ Setting"
description: "설정 및 환경 구성 변경"
labels: ["⚙ Setting"]
type: "Task"
title: "[Setting]: "
body:
  - type: textarea
    attributes:
      label: 🔧 설명
      description: 환경 설정, CI/CD, 빌드 설정 등 하고자 하는 설정에 대해 작성해 주세요.
      placeholder: "예: ESLint 추가, Prettier 설정 변경 등"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🔍 이유
      description: 설정하려는 이유를 설명해주세요.
  - type: textarea
    attributes:
      label: ✅ 작업 항목
      description: 구체적인 변경 작업을 체크리스트로 작성해 주세요.
      value: |
        - [ ] 작업 항목 1
        - [ ] 작업 항목 2
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: 프로젝트의 행동 강령을 준수할 것을 동의해 주세요.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true
  - type: markdown
    attributes:
      value: |
        ## 환경은 프로젝트의 기반입니다.  
        좋은 설정 부탁드립니다 🙌
